[package]
name = "cres"
version = "0.5.0"
description = "Cell resampling for collider events"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
edition = "2021"
license = "GPL-3.0-or-later"
readme = "Readme.md"
keywords = ["physics"]
categories = ["science"]
repository = "https://github.com/a-maier/cres"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argfile = "0.1"
avery = "0.3"
bzip2 = "0.4"
clap = { version = "4.3", features = ["derive"] }
clap_complete = "4.0"
console = "0.15"
derive_builder = "0.12"
dirs = "5.0"
env_logger = "0.10"
flate2 = "1.0"
hepmc2 = "0.5"
indicatif = "0.17"
itertools = "0.11"
jetty = "0.3"
lazy_static = "1.4"
lhef = { version = "0.6", optional = true }
log = "0.4"
logbar = "0.1"
lz4 = "1.23"
noisy_float = "0.2"
ntuple = { version = "0.7", optional = true }
num-traits = "0.2"
particle_id = "0.4"
pathfinding = "4.2"
permutohedron = "0.2"
rand = "0.8"
rand_xoshiro = "0.6"
rayon = "1.5"
regex = "1.5"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
thread_local = "1.1"
typed-builder = "0.15"
zstd = "0.12"

[lib]
name = "cres"
path = "src/lib.rs"
crate-type =["lib", "staticlib", "cdylib"]

[[bin]]
name = "cres"
path = "src/bin/main.rs"

[[bin]]
name = "cres-partition"
path = "src/bin/partition.rs"

[[bin]]
name = "cres-generate-shell-completions"
path = "src/bin/shell_completion.rs"

[features]
default = ["lhef", "multiweight"]
ntuple = ["dep:cc", "dep:bindgen", "dep:ntuple", "avery/ntuple"]
capi = ["multiweight"]
multiweight = []

[build-dependencies]
anyhow = "1.0"
bindgen = { version = "0.66", optional = true }
cbindgen = "0.24"
cc = { version = "1.0", optional = true }
ntuple = { version = "0.7", optional = true }
vergen = { version = "8", features = ["git", "gitcl"] }
