[package]
name = "cres"
version = "0.1.0"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noisy_float = "0.1"
log = "0.4"
env_logger = "0.8"
permutohedron = "0.2"
rayon = "1.5"
logbar = "0.1"
indicatif = "0.15"
console = "0.14"
