[package]
name = "cres"
version = "0.3.3"
description = "Cell resampling for collider events"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
edition = "2021"
license = "GPL-3.0-or-later"
readme = "Readme.md"
keywords = ["physics"]
categories = ["science"]
repository = "https://github.com/a-maier/cres"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bzip2 = "0.4"
clap = { version = "3.1", features = ["derive"] }
console = "0.15"
derive_builder = "0.11"
env_logger = "0.9"
flate2 = "1.0"
hepmc2 = "0.5"
indicatif = "0.16"
jetty = "0.2"
lazy_static = "1.4"
log = "0.4"
logbar = "0.1"
lz4 = "1.23"
noisy_float = "0.2"
permutohedron = "0.2"
rand = "0.8"
rand_xoshiro = "0.6"
rayon = "1.5"
regex = "1.5"
thiserror = "1.0"
thread_local = "1.1"
zstd = "0.11"
num-traits = "0.2"

[lib]
name = "cres"
path = "src/lib.rs"
crate-type =["lib", "staticlib", "cdylib"]

[[bin]]
name = "cres"
path = "src/bin/main.rs"

[features]
ntuple = ["dep:cc", "dep:bindgen"]

[build-dependencies]
anyhow = "1.0"
bindgen = { version = "0.60", optional = true }
cbindgen = "0.21"
cc = { version = "1.0", optional = true }
vergen = "7"
