[package]
name = "cres"
version = "0.1.0"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
edition = "2018"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noisy_float = "0.2"
log = "0.4"
env_logger = "0.9"
permutohedron = "0.2"
rayon = "1.5"
logbar = "0.1"
indicatif = "0.16"
console = "0.14"
hepmc2 = "0.4"
jetty = "0.2"
bzip2 = "0.4"
structopt = "0.3"
flate2 = "1.0"
zstd = "0.9.0"
lz4 = "1.23"
rand = "0.8"
rand_xoshiro = "0.6"
regex = "1.5"
lazy_static = "1.4"

[lib]
name = "cres"
path = "src/lib.rs"

[[bin]]
name = "cres"
path = "src/bin/main.rs"
